version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV-development}
    command: yarn run start-watch
    environment:
      NODE_ENV: ${NODE_ENV-development}
      SEARCH_API_HOST: ${SEARCH_API_HOST}
      SEARCH_API_KEY: ${SEARCH_API_KEY}
      SEARCH_API_VERSION: ${SEARCH_API_VERSION}

  frontend:
    extends:
      service: base-app
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - node_modules:/code/node_modules
      - .:/code

volumes:
  node_modules:
