version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV-development}
    command: yarn run start-watch
    environment:
      NODE_ENV: ${NODE_ENV-development}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}

  frontend:
    extends:
      service: base-app
    links:
      - sexual-health-service-finder-db:es
    ports:
      - 3000:3000
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  sexual-health-service-finder-db:
    image: "nhsuk/elasticsearch-updater-snapshot:${elasticsearch_updater_snapshot_docker_image_tag-20180403}"

volumes:
  node_modules:
