#!/bin/bash

if [ ! -f "./rancher" ] ; then
  : "${RANCHER_CLI_VERSION:=v0.6.13}"

  echo "Installing Rancher (${RANCHER_CLI_VERSION})"
  curl -Ls https://github.com/rancher/cli/releases/download/${RANCHER_CLI_VERSION}/rancher-linux-amd64-${RANCHER_CLI_VERSION}.tar.gz | tar xzf -
  mv rancher-${RANCHER_CLI_VERSION}/rancher ./rancher
  rm -r rancher-${RANCHER_CLI_VERSION}
fi
