#!/bin/bash

# shellcheck source=set-branch-variables
. ./scripts/devops/set-branch-variables

# shellcheck source=get-vault-variables
./scripts/devops/get-vault-variables

# Export all env vars
set -o allexport
# shellcheck disable=SC1091
source answers.txt
set +o allexport
