#!/bin/bash

# Set env vars used by Coveralls
export COVERALLS_SERVICE_NAME='Azure Devops'
export COVERALLS_REPO_TOKEN
COVERALLS_REPO_TOKEN=$(PIPELINE_COVERALLS_REPO_TOKEN)
./test-ci

if [ -n "$CUSTOM_PRID" ]; then
  export CI_PULL_REQUEST=$CUSTOM_PRID
  export BRANCH=${SYSTEM_PULLREQUEST_TARGETBRANCH#refs/heads}
elif [ -n "$CUSTOM_BRANCH" ]; then
  export BRANCH=$CUSTOM_BRANCH
elif [ -n "$CUSTOM_TAG" ]; then
  export BRANCH=$CUSTOM_TAG
else
  echo 'could not determine branch' >&2
  exit 1
fi
