#!/bin/bash

pushd ./test/performance/ || exit 1
JMETER_PATH=../../jmeter/bin/jmeter
TEST_NAME=chlamydia-finder

# Remove pre-existing artifacts
rm ./$TEST_NAME.jtl
rm -rf ./dashboards
mkdir ./dashboards

# Run test and generate dashboard
$JMETER_PATH -n -t ./$TEST_NAME.jmx -Jhostname="nhswebsite-staging.nhs.uk" -Jusers=10 -Jrampup=60 -Jduration=30 -Jthroughput=30 -Jpostcodes=outcodes.csv -l $TEST_NAME.jtl -e -o ./dashboards

popd || exit 1
