#!/bin/bash

CLEANED_SOURCEBRANCH=$(echo "$BUILD_SOURCEBRANCH" | sed -e's:["/:<>\|!?@*]:-:g')
echo "CLEANED_SOURCEBRANCH: $CLEANED_SOURCEBRANCH"

BRANCH=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-heads-(.+)$:\1:p')
echo "BRANCH: $BRANCH"
echo "##vso[task.setvariable variable=BRANCH]$BRANCH"

PRID=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-pull-([0-9]+)-merge$:\1:p')
echo "PRID: $PRID"
echo "##vso[task.setvariable variable=PRID]$PRID"

TAG=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-tags-(.+)$:\1:p')
echo "TAG: $TAG"
echo "##vso[task.setvariable variable=TAG]$TAG"

{
  echo "BRANCH=$BRANCH"
  echo "PRID=$PRID"
  echo "TAG=$TAG"
} >> answers.txt
