#!/bin/bash

CLEANED_SOURCEBRANCH=$(echo "$BUILD_SOURCEBRANCH" | sed -e's:["/:<>\|!?@*]:-:g')
BRANCH=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-heads-(.+)$:\1:p')
PRID=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-pull-([0-9]+)-merge$:\1:p')
TAG=$(echo "$CLEANED_SOURCEBRANCH" | sed -E -n -e's:^refs-tags-(.+)$:\1:p')

if [ -n "$BRANCH" ]; then
  echo "##vso[task.setvariable variable=CUSTOM_BRANCH]$BRANCH"
  PARTIAL_BUILD_NAME="$BRANCH"
fi

if [ -n "$PRID" ]; then
  echo "##vso[task.setvariable variable=CUSTOM_PRID]$PRID"
  PARTIAL_BUILD_NAME="PR-$PRID"
fi

if [ -n "$TAG" ]; then
  echo "##vso[task.setvariable variable=CUSTOM_TAG]$TAG"
  PARTIAL_BUILD_NAME="$TAG"
fi

if [ -n "$PARTIAL_BUILD_NAME" ]; then
  BUILD_NAME="$PARTIAL_BUILD_NAME - $BUILD_BUILDNUMBER"
  echo "##vso[build.updatebuildnumber]$BUILD_NAME"
fi

# Set env vars used by Coveralls
export COVERALLS_SERVICE_NAME='Azure Devops'
COVERALLS_REPO_TOKEN=$(PIPELINE_COVERALLS_REPO_TOKEN)
echo "COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN"
export COVERALLS_REPO_TOKEN

if [ -n "$CUSTOM_PRID" ]; then
  export CI_PULL_REQUEST=$CUSTOM_PRID
  export BRANCH=${SYSTEM_PULLREQUEST_TARGETBRANCH#refs/heads}
elif [ -n "$CUSTOM_BRANCH" ]; then
  export BRANCH=$CUSTOM_BRANCH
elif [ -n "$CUSTOM_TAG" ]; then
  export BRANCH=$CUSTOM_TAG
else
  echo 'Could not determine branch. Exiting...' >&2
  exit 1
fi
