#!/bin/bash
# Specifying the project name (-p) creates a non-default network for the tests
# to run isolated from the main app
PROJECT_NAME=test-ci
docker-compose -p $PROJECT_NAME -f docker-compose-tests.yml down -v
docker-compose -p $PROJECT_NAME -f docker-compose-tests.yml build $PROJECT_NAME
docker-compose -p $PROJECT_NAME -f docker-compose-tests.yml run $PROJECT_NAME
# Copy coverage from the image to the host
docker cp "$(docker ps -af 'name=$PROJECT_NAME' --format '{{.ID}}'):/code/coverage/" .
# Rewrite report to account for the code not being contained in 'code' dir outside of container
sed -i -e 's:/code/:./:' ./coverage/lcov.info
# Install coveralls into the CI container to perform upload
mkdir run-coveralls && cd run-coveralls && npm init -f && npm install coveralls && cd ..
./run-coveralls/node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info

# Clean up
rm -rf run-coveralls
